openapi: "3.0.2"
info:
  title: Test API
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /:
    get:
      responses:
        "200":
          description: OK
  /health:
    get:
      responses:
        "200":
          description: OK
  /submit/{id}:
    post:
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/CodeSubmission"
                - $ref: "#/components/schemas/TextSubmission"
                - $ref: "#/components/schemas/EventStreamSubmission"
      responses:
        "200":
          description: The submission results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubmissionResult"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
                
components:
  schemas:
    TextSubmission:
      properties:
        type:
          type: string
          enum:
            - text
          nullable: false
        submission:
          type: string
          nullable: false
    CodeSubmission:
      properties:
        type:
          type: string
          enum:
            - code
          nullable: false
        submission:
          type: string
          nullable: false
    EventStreamSubmission:
      properties:
        type:
          type: string
          enum:
            - eventStream
          nullable: false
        submission:
          type: array
          items:
            anyOf:
              - $ref: "#/components/schemas/VisitNodeEvent"
              - $ref: "#/components/schemas/AddNodeEvent"
          nullable: false
    VisitNodeEvent:
      properties:
        type:
          type: string
          enum:
            - visitNode
          nullable: false
        id:
          type: string
          nullable: false
    AddNodeEvent:
      properties:
        type:
          type: string
          enum:
            - visitNode
          nullable: false
        parentId:
          type: string
          nullable: false
        node:
          type: object
          properties:
            id:
              type: string
              nullable: false
            data:
              type: object
              nullable: false
          nullable: false
    SubmissionResult:
      properties:
        result:
          $ref:  "#/components/schemas/Result"
        tests:
          type: array
          items:
            $ref:  "#/components/schemas/TestResult"
    Result:
      type: string
      enum:
        - success
        - fail
    TestResult:
      properties:
        name:
          type: string
        reason:
          type: string
        result:
          $ref:  "#/components/schemas/Result"
    Error:
      properties:
        code:
          type: integer
          format: int32
          nullable: false
        message:
          type: string
          nullable: false
        reason:
          type: string
  responses:
    BadRequest:
      description: Bad request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Entity not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    GeneralError:
      description: General Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'