name: Docker Image CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker image
      run: docker build . -t ag-api:$GITHUB_RUN_ID
    - uses: actions/checkout@v2
    - name: Lint
      run: docker run ag-api:$GITHUB_RUN_ID npm run lint
    - name: Run tests
      run: docker run ag-api:$GITHUB_RUN_ID npm run test
    
