name: Docker Image CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . -t node-docker-heroku-cicd:$GITHUB_RUN_ID
    - name: Lint
      run: docker run -p 3000:3000 node-docker-heroku-cicd:$GITHUB_RUN_ID npm run lint
    - name: Run tests
      run: docker run -p 3000:3000 node-docker-heroku-cicd:$GITHUB_RUN_ID npm run test
    
